parameters:

    #
    # Parameters
    #
    gearman.cache.id: gearman.workers

    #
    # Generators
    #
    gearman.unique_job_identifier.class: Mkk\GearmanBundle\Generator\UniqueJobIdentifierGenerator

    #
    # Dispatchers
    #
    gearman.dispatcher.callbacks.class: Mkk\GearmanBundle\Dispatcher\GearmanCallbacksDispatcher

    #
    # Services
    #
    gearman.client.class:        Mkk\GearmanBundle\Service\GearmanClient
    gearman.callbacks.class:     Mkk\GearmanBundle\Service\GearmanCallbacks
    gearman.execute.class:       Mkk\GearmanBundle\Service\GearmanExecute
    gearman.describer.class:     Mkk\GearmanBundle\Service\GearmanDescriber
    gearman.parser.class:        Mkk\GearmanBundle\Service\GearmanParser
    gearman.cache.wrapper.class: Mkk\GearmanBundle\Service\GearmanCacheWrapper

    #
    # Commands
    #
    gearman.command.cache_clear.class:     Mkk\GearmanBundle\Command\GearmanCacheClearCommand
    gearman.command.cache_warmup.class:    Mkk\GearmanBundle\Command\GearmanCacheWarmupCommand
    gearman.command.job_describe.class:    Mkk\GearmanBundle\Command\GearmanJobDescribeCommand
    gearman.command.job_execute.class:     Mkk\GearmanBundle\Command\GearmanJobExecuteCommand
    gearman.command.worker_describe.class: Mkk\GearmanBundle\Command\GearmanWorkerDescribeCommand
    gearman.command.worker_execute.class:  Mkk\GearmanBundle\Command\GearmanWorkerExecuteCommand
    gearman.command.worker_list.class:     Mkk\GearmanBundle\Command\GearmanWorkerListCommand

    #
    # Externals
    #
    gearman.external.symfony_finder.class:  Symfony\Component\Finder\Finder
