services:

    #
    # Generators
    #
    gearman.unique_job_identifier:
        class: "%gearman.unique_job_identifier.class%"
        arguments:
            - "%gearman.default.settings.generate_unique_key%"
