sudo: required
dist: trusty

language: php
php:
    - '5.5'
    - '5.6'
    - '7.0'
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

install:
  - sh -c "sudo apt-get -y install uuid-dev libgearman-dev gearman gearman-job-server"
before_script:
  - curl -L -o gearman-2.0.1.tgz https://github.com/wcgallego/pecl-gearman/archive/gearman-2.0.1.tar.gz
  - tar -xzf gearman-2.0.1.tgz
  - sh -c "cd pecl-gearman-gearman-2.0.1 && phpize && ./configure && make && sudo make install && cd .."
  - echo "extension=gearman.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install --prefer-source --no-interaction

script:
  - php vendor/bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    email: false
